name: Claude Code

on:
  issues:
    types: [opened, assigned]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

jobs:
  claude-code:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review_comment' && contains(github.event.comment.body, '@claude')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@claude')) ||
      (github.event_name == 'issues' && (contains(github.event.issue.body, '@claude') || contains(github.event.issue.title, '@claude')))
    # [Important] For accessing AWS Bedrock
    environment: claude
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.CLAUDE_CODE_AWS_ROLE }}
          aws-region: us-east-1
      - uses: anthropics/claude-code-action@v1
        env:
          # [Important] For using Bedrock in Claude Code
          AWS_REGION: us-east-1
          # Use Sonnet 4.5 for the default model
          ANTHROPIC_DEFAULT_SONNET_MODEL: ${BEDROCK_ARN_PREFIX}/9d7sekky2cm6
          # Use Haiku 4.5 for small tasks
          ANTHROPIC_DEFAULT_HAIKU_MODEL: ${BEDROCK_ARN_PREFIX}/ls66k5wvo4vk
        with:
          use_bedrock: "true"
          # This is an optional setting that allows Claude to read CI results on PRs
          additional_permissions: |
            actions: read
          # Use Sonnet 4.5 [1m] as the default model
          claude_args: |
            --model "sonnet[1m]"
            --allowedTools "mcp__github__create_pull_request,mcp__github__create_pending_pull_request_review,mcp__github__add_pull_request_review_comment_to_pending_review,mcp__github__submit_pending_pull_request_review,mcp__github__get_pull_request_diff,mcp__github__add_comment_to_pending_review,mcp__github_inline_comment__create_inline_comment,Bash(gh pr comment:*),Bash(gh pr diff:*),Bash(gh pr view:*),Bash(gh pr review:*),Read,Grep"
